// ДАНІ ДЛЯ СЛАЙДЕРА НОВИН
const newsSlides = [
    {
        id: "judgment-early-access",
        badge: "РАННІЙ ДОСТУП",
        badge_en: "EARLY ACCESS",
        badgeType: "announcement",
        title: "Judgment — безкоштовний первинний доступ!",
        title_en: "Judgment — Free Primary Access!",
        description: "Почався безкоштовний первинний доступ до українізатора Judgment! Гру вже можна пройти від початку й до кінця українською мовою!",
        description_en: "Free primary access to the Judgment Ukrainian localization has begun! You can now play the full story and side cases in Ukrainian!",
        image: "assets/judgment_news.webp",
        link: "https://www.dropbox.com/scl/fi/s7baju60jm5qlb5h123m8/Judgment.exe?rlkey=o36lfpwfcr4tlhdvetxgyulwd&st=be1lsyov&dl=1",
        buttonText: "Завантажити",
        buttonText_en: "Download"
    },
    {
        id: "uncharted1-early-access",
        badge: "РАННІЙ ДОСТУП",
        badge_en: "EARLY ACCESS",
        badgeType: "announcement",
        title: "Uncharted: Drake's Fortune — ранній доступ!",
        title_en: "Uncharted: Drake's Fortune — Early Access!",
        description: "Легендарна пригода Дрейка українською! Перший великий ексклюзив для PS3, який започаткував культову пригодницьку серію від Naughty Dog, тепер доступний для завантаження.",
        description_en: "Nathan Drake's legendary adventure in Ukrainian! The first major PS3 exclusive that launched the iconic Naughty Dog series is now available for download.",
        image: "assets/Uncharted1_news.webp",
        link: "https://donatello.to/LittleBitUA",
        buttonText: "Детальніше",
        buttonText_en: "Learn More"
    },
    {
        id: "dispatch-update",
        badge: "ОНОВЛЕННЯ",
        badge_en: "UPDATE",
        badgeType: "update",
        title: "Dispatch — оновлення українізатора",
        title_en: "Dispatch — Localization Updated",
        description: "Оновлено переклад Dispatch: виправлено помилки та зламані рядки після оновлення гри. Якщо ще не грали — саме час!",
        description_en: "Dispatch localization updated: fixed errors and broken strings after the latest game patch. If you haven't played yet, now's the time!",
        image: "assets/Dispatch_news.webp",
        link: "https://littlebitua.github.io/",
        buttonText: "Детальніше",
        buttonText_en: "Learn More"
    },
    {
        id: "yakuza-lad-fundraising",
        badge: "ЗБІР КОШТІВ",
        badge_en: "FUNDRAISING",
        badgeType: "progress",
        title: "Yakuza: Like a Dragon — збір на локалізацію",
        title_en: "Yakuza: Like a Dragon — Localization Fundraising",
        description: "Триває збір коштів на повну текстову локалізацію Yakuza: Like a Dragon українською. Частину гри вже перекладено, долучайтеся до підтримки!",
        description_en: "We are raising funds for a full Ukrainian text localization of Yakuza: Like a Dragon. Part of the game is already translated—support the project!",
        image: "assets/YakuzaLAD_news.webp",
        link: "https://donatello.to/LittleBitUA",
        buttonText: "Підтримати",
        buttonText_en: "Support"
    },
    {
        id: "nier-replicant-fundraising",
        badge: "ЗБІР КОШТІВ",
        badge_en: "FUNDRAISING",
        badgeType: "progress",
        title: "NieR Replicant — збір на локалізацію",
        title_en: "NieR Replicant — Localization Fundraising",
        description: "Збираємо кошти на українську локалізацію NieR Replicant. Атмосферна дія з глибоким сюжетом та музикою заслуговує на українські субтитри.",
        description_en: "We are raising funds for the Ukrainian localization of NieR Replicant. This atmospheric action game with a deep story and soundtrack deserves Ukrainian subtitles.",
        image: "assets/NieR_news.webp",
        link: "https://donatello.to/LittleBitUA",
        buttonText: "Підтримати",
        buttonText_en: "Support"
    },
    {
        id: "mgs2-fundraising",
        badge: "ЗБІР КОШТІВ",
        badge_en: "FUNDRAISING",
        badgeType: "progress",
        title: "Metal Gear Solid 2 — збір та переклад продовжується!",
        title_en: "Metal Gear Solid 2 — Fundraising and Translation Continues!",
        description: "Збираємо кошти на повну текстову українську локалізацію!",
        description_en: "Raising funds for full Ukrainian text localization!",
        image: "assets/MGS2_news.webp",
        link: "https://donatello.to/LittleBitUA",
        buttonText: "Підтримати",
        buttonText_en: "Support"
    }
];
